SELECT C.ZONE_NAME , C.AREA_NAME, C.COMPANY_BRANCH_NAME BRANCH_NAME
        , A.COMPANY_BRANCH_CODE BRANCH_CODE 
        , A.MNYR, A.TRANS_DAY,  A.RCVBLE_PRN, A.REGR_RCVD_PRN, A.ADV_ADJ_PRN
        , ROUND(A.REGR_RCVD_PRN / ( NVL(A.RCVBLE_PRN,0) +  NVL(A.ADV_ADJ_PRN,0)) , 4)  * 100 BEF_D_CLS_OTR
        , TD_RCVBLE_PRN, TD_REG_RCVD_PRN, TD_ADV_ADJ_PRN, OTR_DAY_PRN
        --, LOAN_DUE_RCVD, LOAN_ADV_RCVD,  TD_RCVBLE_PRN, TD_REG_RCVD_PRN, TD_ADV_ADJ_PRN
        , ROUND(CD.REGR_RCVD_PRN / ( NVL(CD.RCVBLE_PRN,0) +  NVL(CD.ADV_ADJ_PRN,0)) , 4)  * 100 AFT_D_CLS_OTR
FROM 
    (
    SELECT COMPANY_CODE , COMPANY_BRANCH_CODE ,TRANS_DAY,  MNYR, FINANCE_CODE, PROJECT_CODE, COMPONENT_CODE 
            ,   NVL(SUM(RECEIVABLE_PRN),0) RCVBLE_PRN , NVL(SUM(REG_RCVD_PRN),0) REGR_RCVD_PRN, NVL(SUM(ADVANCE_ADJ_PRN),0) ADV_ADJ_PRN
           
            , NVL(SUM(TD_RCVBLE_WSC),0) TD_RCVBLE_WSC  , NVL(SUM(TD_REG_RCVD_WSC),0) LOAN_REG_RCVD , NVL(SUM(TD_DUE_RCVD_WSC),0) LOAN_DUE_RCVD
            , NVL(SUM(TD_ADV_RCVD_WSC),0) LOAN_ADV_RCVD , NVL(SUM(TD_ADV_ADJ_WSC),0) ADVANCE_ADJUST 
            
            , ROUND((NVL(SUM(TD_REG_RCVD_WSC),0) + NVL(SUM(TD_ADV_ADJ_WSC),0)) / DECODE(NVL(SUM(TD_RCVBLE_WSC),0), 0 , 1, SUM(TD_RCVBLE_WSC))  ,4) * 100 OTR_DAY
            
     
            , NVL(SUM(TD_RCVBLE_PRN),0) TD_RCVBLE_PRN , NVL(SUM(TD_REG_RCVD_PRN),0) TD_REG_RCVD_PRN , NVL(SUM(TD_ADV_ADJ_PRN),0) TD_ADV_ADJ_PRN
           , ROUND((NVL(SUM(TD_REG_RCVD_PRN),0) + NVL(SUM(TD_ADV_ADJ_PRN),0)) / DECODE(NVL(SUM(TD_RCVBLE_PRN),0), 0 , 1, SUM(TD_RCVBLE_PRN))  ,4) * 100 OTR_DAY_PRN
    FROM MF_LOAN_REALIZATION_DAY
    WHERE COMPANY_CODE = :P0_COMPANY
    AND MNYR = :P0_GLB_MNYR
    --AND COMPANY_BRANCH_CODE = '133'
    AND COMPANY_BRANCH_CODE IN   (SELECT COMPANY_BRANCH_CODE FROM V$USER_BRANCH WHERE  USER_NAME = :APP_USER )
    AND TRANS_DAY = :P0_GLB_OPEN_DATE
    GROUP BY COMPANY_CODE , COMPANY_BRANCH_CODE , TRANS_DAY, MNYR, FINANCE_CODE, PROJECT_CODE, COMPONENT_CODE
    ) A
JOIN COMPANY_BRANCH_INFO C
ON
    (
        A.COMPANY_BRANCH_CODE = C.COMPANY_BRANCH_CODE 
    )
LEFT JOIN
        (
        SELECT COMPANY_CODE , COMPANY_BRANCH_CODE , LAST_CLS_DATE,  MNYR, FINANCE_CODE, PROJECT_CODE, COMPONENT_CODE 
                ,   NVL(SUM(RECEIVABLE_PRN),0) RCVBLE_PRN , NVL(SUM(REG_RCVD_PRN),0) REGR_RCVD_PRN, NVL(SUM(ADVANCE_ADJ_PRN),0) ADV_ADJ_PRN
        FROM  MF_LOAN_REALIZATION
        WHERE MNYR = '08/2024'
        AND LAST_CLS_DATE IS NOT NULL
        GROUP BY COMPANY_CODE , COMPANY_BRANCH_CODE , LAST_CLS_DATE, MNYR, FINANCE_CODE, PROJECT_CODE, COMPONENT_CODE 
        ) CD
ON
    (
        A.COMPANY_CODE = CD.COMPANY_CODE
    AND A.COMPANY_BRANCH_CODE = CD.COMPANY_BRANCH_CODE
    AND A.TRANS_DAY = CD.LAST_CLS_DATE
    AND A.MNYR = CD.MNYR
    AND A.FINANCE_CODE = CD.FINANCE_CODE
    AND A.PROJECT_CODE = CD.PROJECT_CODE
    AND A.COMPONENT_CODE = CD.COMPONENT_CODE
    )
ORDER BY A.COMPANY_BRANCH_CODE
; 
