# MF_LOAN_REALIZATION_DAY Table

This SQL script creates the `MF_LOAN_REALIZATION_DAY` table, which stores Daily loan realization data for microfinance operations

## Table Structure

```sql
CREATE TABLE MF_LOAN_REALIZATION_DAY (
    COMPANY_CODE             VARCHAR2(4),
    COMPANY_BRANCH_CODE      VARCHAR2(4),
    FINANCE_CODE             VARCHAR2(2),
    PROJECT_CODE             VARCHAR2(2),
    COMPONENT_CODE           VARCHAR2(2),
    MNYR                     VARCHAR2(7),
    WKYR                     VARCHAR2(7),
    TRANS_DAY                DATE,
    SAMITY_CODE              VARCHAR2(10),
    MEMBER_ID                VARCHAR2(10),
    LOAN_CODE                VARCHAR2(3),
    DAFA_NO                  NUMBER(8, 0),
    OPENING_LOAN_WSC         NUMBER(15, 0),
    OPENING_DUE_WSC          NUMBER(15, 0),
    OPENING_ADVANCE_WSC      NUMBER(15, 0),
    RECEIVABLE_WSC           NUMBER(15, 0),
    TOTAL_RECEIVED_WSC       NUMBER(15, 0),
    DUE_RCVD_WSC             NUMBER(15, 0),
    REG_RCVD_WSC             NUMBER(15, 0),
    ADV_RCVD_WSC             NUMBER(15, 0),
    OPENING_LOAN_PRN         NUMBER(16, 2),
    OPENING_DUE_PRN          NUMBER(16, 2),
    OPENING_ADVANCE_PRN      NUMBER(16, 2),
    RECEIVABLE_PRN           NUMBER(16, 2),
    TOTAL_RECEIVED_PRN       NUMBER(16, 2),
    DUE_RCVD_PRN             NUMBER(16, 2),
    REG_RCVD_PRN             NUMBER(16, 2),
    ADV_RCVD_PRN             NUMBER(16, 2),
    UPDATE_BY                VARCHAR2(30),
    UPDATE_TIME              TIMESTAMP(6),
    ADVANCE_ADJUST_WSC       NUMBER(16, 0),
    ADVANCE_ADJ_PRN          NUMBER(16, 0),
    MONTH_TTL_RCVBLE_WSC     NUMBER(16, 0),
    MONTH_TTL_RCVBLE_PRN     NUMBER(16, 0),
    MONTH_TTL_REG_RCVD_WSC   NUMBER(16, 0),
    MONTH_TTL_REG_RCVD_PRN   NUMBER(16, 0),
    LOAN_TYPE                VARCHAR2(1),
    RECOVERY_FLAG            VARCHAR2(1),
    RECOVERY_DATE            DATE,
    CLS_LOAN_WSC             NUMBER(15, 0),
    CLS_DUE_WSC              NUMBER(15, 0),
    CLS_ADV_WSC              NUMBER(15, 0),
    CLS_LOAN_PRN             NUMBER(15, 0),
    CLS_DUE_PRN              NUMBER(15, 0),
    CLS_ADV_PRN              NUMBER(15, 0),
    LLP_AGE_CODE_OPN         VARCHAR2(2),
    LLP_PCT_OPN              NUMBER,
    LLP_DAYS_OPN             NUMBER(12, 0),
    INSTALL_AMT              NUMBER(12, 0),
    LLP_CM_DAYS              NUMBER(12, 0),
    LLP_CLASS_OPN            VARCHAR2(2),
    CM_DUE_WSC               NUMBER(12, 0),
    CM_DUE_PRN               NUMBER(12, 0),
    LLP_CUR_DAYS             NUMBER(8, 0),
    LLP_CUR_CLASS            VARCHAR2(2),
    DISBURSE_DATE            DATE,
    DISBURSE_AMT             NUMBER(12, 0),
    NEW_DISBURSE_FLAG        CHAR(1),
    TR_OUT_FLAG              VARCHAR2(1),
    TR_IN_FLAG               VARCHAR2(1),
    CO_ID                    VARCHAR2(10),
    DISBURSE_AMT_WSC         NUMBER(15, 0),
    TD_RCVBLE_WSC            NUMBER(15, 0),
    TD_REG_RCVD_WSC          NUMBER(15, 0),
    TD_DUE_RCVD_WSC          NUMBER(15, 0),
    TD_ADV_RCVD_WSC          NUMBER(15, 0),
    TD_ADV_ADJ_WSC           NUMBER(15, 0),
    TD_TTL_RCVD_WSC          NUMBER(15, 0),
    TD_SAMITY_FLAG           VARCHAR2(1),
    REBATE_AMT               NUMBER(12, 0),
    CM_ADVANCE_WSC           NUMBER(15, 0),
    CM_ADVANCE_PRN           NUMBER(15, 2),
    TR_OUT_LOAN_WSC          NUMBER(15, 0),
    TR_OUT_LOAN_PRN          NUMBER(16, 2),
    TR_IN_LOAN_WSC           NUMBER(15, 0),
    TR_IN_LOAN_PRN           NUMBER(16, 2),
    TRANSFER_DATE            DATE,
    TR_OUT_DUE_WSC           NUMBER(15, 0),
    TR_OUT_DUE_PRN           NUMBER(16, 2),
    TR_IN_DUE_WSC            NUMBER(15, 0),
    TR_IN_DUE_PRN            NUMBER(16, 2),
    TD_RCVBLE_PRN            NUMBER(16, 2),
    TD_REG_RCVD_PRN          NUMBER(16, 2),
    TD_DUE_RCVD_PRN          NUMBER(16, 2),
    TD_ADV_RCVD_PRN          NUMBER(16, 2),
    TD_ADV_ADJ_PRN           NUMBER(16, 2),
    TD_TTL_RCVD_PRN          NUMBER(16, 2),
    TD_DISBURSE              NUMBER(16, 0),
    CONSTRAINT MF_LN_RDRA_DAY_PK PRIMARY KEY (
        COMPANY_CODE,
        COMPANY_BRANCH_CODE,
        FINANCE_CODE,
        PROJECT_CODE,
        COMPONENT_CODE,
        MNYR,
        WKYR,
        TRANS_DAY,
        SAMITY_CODE,
        MEMBER_ID,
        LOAN_CODE,
        DAFA_NO
    )
);
