CREATE TABLE MF_LRPS_ARCHIVE (
    COMPANY_CODE          VARCHAR2(4) NOT NULL ENABLE,
    COMPANY_BRANCH_CODE   VARCHAR2(6) NOT NULL ENABLE,
    SAMITY_CODE           VARCHAR2(10) NOT NULL ENABLE,
    MEMBER_ID             VARCHAR2(10) NOT NULL ENABLE,
    LOAN_CODE             VARCHAR2(10) NOT NULL ENABLE,
    DAFA_NO               NUMBER(2,0) NOT NULL ENABLE,
    SCHEDULE_SL           NUMBER(1,0) NOT NULL ENABLE,
    INSTALL_NO            NUMBER(4,0) NOT NULL ENABLE,
    INSTALL_DT            DATE,
    WKYR                  VARCHAR2(7),
    MNYR                  VARCHAR2(7) NOT NULL ENABLE,
    INSTALL_AMT           NUMBER(12,2),
    PRN_AMT               NUMBER(12,2),
    SC_AMT                NUMBER(12,2),
    USERID                VARCHAR2(15),
    ENTRDT                DATE,
    LAST_USERID           VARCHAR2(15),
    UPDDT                 DATE,
    FINANCE_CODE          VARCHAR2(2) NOT NULL ENABLE,
    PROJECT_CODE          VARCHAR2(2) NOT NULL ENABLE,
    COMPONENT_CODE        VARCHAR2(3) NOT NULL ENABLE,
    ACC_CLOSE_FLAG        VARCHAR2(1),
    ACC_CLOSE_DATE        DATE,
    INSTALL_TYPE          VARCHAR2(1),
    BAL_DATE              DATE,
    PRN_AMT_EXTENDED      NUMBER(15,8),
    INS_USER              VARCHAR2(50),
    INS_DATE              DATE,
    UPD_USER              VARCHAR2(50),
    UPD_DATE              DATE,
    SC_OD                 NUMBER(15,7),
    CONSTRAINT MF_LRPS_ARCHIVE_PK PRIMARY KEY ( COMPANY_CODE,
                                                  COMPANY_BRANCH_CODE,
                                                  SAMITY_CODE,
                                                  MEMBER_ID,
                                                  LOAN_CODE,
                                                  DAFA_NO,
                                                  SCHEDULE_SL,
                                                  INSTALL_NO,
                                                  FINANCE_CODE,
                                                  PROJECT_CODE,
                                                  COMPONENT_CODE,
                                                  MNYR )
);
