create or replace PROCEDURE      UPDATE_LOAN_SCHEDULE_JOB_PROC
 IS

 V_MNYR VARCHAR2(7);
BEGIN              
    SELECT GET_PERIOD_STARTYR(TO_DATE(SYSDATE, 'DD-MON-RR')) A
            INTO V_MNYR
        FROM DUAL;


        DELETE MF_LRPS_ARCHIVE
        WHERE MNYR = V_MNYR
        ;
        COMMIT;
       INSERT INTO  MF_LRPS_ARCHIVE
        SELECT COMPANY_CODE , COMPANY_BRANCH_CODE , SAMITY_CODE ,MEMBER_ID , LOAN_CODE , DAFA_NO ,
        SCHEDULE_SL , INSTALL_NO , INSTALL_DT , WKYR , MNYR ,
        INSTALL_AMT , PRN_AMT , SC_AMT ,
        USERID , ENTRDT , LAST_USERID , UPDDT ,
        FINANCE_CODE , PROJECT_CODE , COMPONENT_CODE ,
        ACC_CLOSE_FLAG , ACC_CLOSE_DATE , INSTALL_TYPE , BAL_DATE ,
        PRN_AMT_EXTENDED , 'AUTO_PROCESS' , SYSDATE , UPD_USER , UPD_DATE ,SC_OD 
        FROM LOAN_REPAY_SCHEDULE
        WHERE COMPANY_CODE = COMPANY_CODE--'0020'
        AND MNYR = V_MNYR
       -- AND (ACC_CLOSE_DATE IS NULL
         --   OR ACC_CLOSE_DATE BETWEEN '01-AUG-20' AND '31-AUG-20')
        ;
        COMMIT;      
END;
