SELECT  
    COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO 
    , OPENING_LOAN_WSC , OPENING_DUE_WSC , OPENING_ADVANCE_WSC
    , RECEIVABLE_WSC , TOTAL_RECEIVED_WSC
    ----------------------------------------------------------------------------------------------------------- TODAY'S OTR WSC
    ,  NVL(CASE  WHEN TODAYS_RCVBLE > 0 AND  TD_TTL_RCVD <= TODAYS_RCVBLE THEN  TD_TTL_RCVD  
    WHEN TODAYS_RCVBLE > 0 AND  TD_TTL_RCVD > TODAYS_RCVBLE THEN  TODAYS_RCVBLE
    END,0) TD_REG_RCVD_WSC
    
    , NVL(CASE  WHEN OPENING_DUE_WSC > 0 AND TD_TTL_RCVD >=  TODAYS_RCVBLE + OPENING_DUE_WSC THEN OPENING_DUE_WSC
    WHEN OPENING_DUE_WSC > 0 AND TD_TTL_RCVD > TODAYS_RCVBLE AND TD_TTL_RCVD <=  TODAYS_RCVBLE + OPENING_DUE_WSC 
    THEN TD_TTL_RCVD - TODAYS_RCVBLE
    END, 0) TD_DEU_RCVD_WSC
    , NVL(CASE 
    WHEN TD_TTL_RCVD > OPENING_DUE_WSC + TODAYS_RCVBLE THEN TD_TTL_RCVD  - (OPENING_DUE_WSC + TODAYS_RCVBLE)
    WHEN OPENING_DUE_WSC = 0 AND TD_TTL_RCVD > TODAYS_RCVBLE THEN TD_TTL_RCVD - TODAYS_RCVBLE
    END,0) TD_ADV_RCVD_WSC
    
    , NVL(CASE 
    WHEN OPENING_ADVANCE_WSC > 0 AND  TD_TTL_RCVD < TODAYS_RCVBLE AND OPENING_ADVANCE_WSC <= TODAYS_RCVBLE  - TD_TTL_RCVD 
    THEN OPENING_ADVANCE_WSC
    WHEN OPENING_ADVANCE_WSC > 0 AND TD_TTL_RCVD < TODAYS_RCVBLE AND OPENING_ADVANCE_WSC > TODAYS_RCVBLE  - TD_TTL_RCVD 
    THEN TODAYS_RCVBLE - TD_TTL_RCVD
    --TODAYS_RCVBLE
    WHEN  TODAYS_RCVBLE > 0 AND TD_TTL_RCVD = 0 AND RECEIVABLE_WSC <= PRV_TTL_RCVD THEN  TODAYS_RCVBLE -- CORRECTION FOR INCORRECT ADVANCE ADJUST AMOUNT 30112023
    --WHEN  TODAYS_RCVBLE > 0 AND TD_TTL_RCVD > 0 AND TD_TTL_RCVD < TODAYS_RCVBLE  AND TODAYS_RCVBLE <= PRV_TTL_RCVD THEN  TODAYS_RCVBLE
    END,0) TD_ADVANCE_ADJUST_WSC
    ------------------------------------------------------------------------------------------------------------------------------ TODAYS'S OTR PRN
    
    ,  NVL(CASE  WHEN TODAYS_RCVBLE_PRN > 0 AND  TD_TTL_RCVD_PRN <= TODAYS_RCVBLE_PRN THEN  TD_TTL_RCVD_PRN  
    WHEN TODAYS_RCVBLE_PRN > 0 AND  TD_TTL_RCVD_PRN > TODAYS_RCVBLE_PRN THEN  TODAYS_RCVBLE_PRN
    END,0) TD_REG_RCVD_PRN
    
    , NVL(CASE  WHEN OPENING_LOAN_PRN > 0 AND TD_TTL_RCVD_PRN >=  TODAYS_RCVBLE_PRN + OPENING_LOAN_PRN THEN OPENING_LOAN_PRN
    WHEN OPENING_LOAN_PRN > 0 AND TD_TTL_RCVD_PRN > TODAYS_RCVBLE_PRN AND TD_TTL_RCVD_PRN <=  TODAYS_RCVBLE_PRN + OPENING_LOAN_PRN 
    THEN TD_TTL_RCVD_PRN - TODAYS_RCVBLE_PRN
    END, 0) TD_DEU_RCVD_PRN
    ------------------------------------------------------------------------------------------------------------
    ,  NVL(CASE  WHEN RECEIVABLE_WSC > 0 AND  TOTAL_RECEIVED_WSC <= RECEIVABLE_WSC THEN  TOTAL_RECEIVED_WSC  
    WHEN RECEIVABLE_WSC > 0 AND  TOTAL_RECEIVED_WSC > RECEIVABLE_WSC THEN  RECEIVABLE_WSC
    END,0)REG_RCVD_WSC_NEW
    
    , NVL(CASE  WHEN OPENING_DUE_WSC > 0 AND TOTAL_RECEIVED_WSC >=  RECEIVABLE_WSC + OPENING_DUE_WSC THEN OPENING_DUE_WSC
    WHEN OPENING_DUE_WSC > 0 AND TOTAL_RECEIVED_WSC > RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC <=  RECEIVABLE_WSC + OPENING_DUE_WSC 
    THEN TOTAL_RECEIVED_WSC - RECEIVABLE_WSC
    -- WHEN OPENING_DUE_WSC > 0 AND RECEIVABLE_WSC = 0  AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC THEN TOTAL_RECEIVED_WSC
    
    END, 0)DEU_RCVD_WSC_NEW
    
    , NVL(CASE 
    WHEN TOTAL_RECEIVED_WSC > OPENING_DUE_WSC + RECEIVABLE_WSC THEN TOTAL_RECEIVED_WSC  - (OPENING_DUE_WSC + RECEIVABLE_WSC)
    WHEN OPENING_DUE_WSC = 0 AND TOTAL_RECEIVED_WSC > RECEIVABLE_WSC THEN TOTAL_RECEIVED_WSC - RECEIVABLE_WSC
    END,0) ADV_RCVD_WSC_NEW
    , NVL(CASE 
    WHEN OPENING_ADVANCE_WSC > 0 AND  TOTAL_RECEIVED_WSC < RECEIVABLE_WSC AND OPENING_ADVANCE_WSC <= RECEIVABLE_WSC  - TOTAL_RECEIVED_WSC 
    THEN OPENING_ADVANCE_WSC
    
    WHEN OPENING_ADVANCE_WSC > 0 AND TOTAL_RECEIVED_WSC < RECEIVABLE_WSC AND OPENING_ADVANCE_WSC > RECEIVABLE_WSC  - TOTAL_RECEIVED_WSC 
    THEN RECEIVABLE_WSC - TOTAL_RECEIVED_WSC
    END,0) ADVANCE_ADJUST_WSC_NEW
    -----------------------------------------------------------------------------------------
    , RECEIVABLE_PRN ,  TOTAL_RECEIVED_PRN 
    ,  NVL(CASE  WHEN RECEIVABLE_PRN > 0 AND  TOTAL_RECEIVED_PRN <= RECEIVABLE_PRN THEN  TOTAL_RECEIVED_PRN  
    WHEN RECEIVABLE_PRN > 0 AND  TOTAL_RECEIVED_PRN > RECEIVABLE_PRN THEN  RECEIVABLE_PRN
    END,0)REG_RCVD_PRN_NEW
    
    , NVL(CASE  WHEN OPENING_DUE_PRN > 0 AND TOTAL_RECEIVED_PRN >=  RECEIVABLE_PRN + OPENING_DUE_PRN THEN OPENING_DUE_PRN
    WHEN OPENING_DUE_PRN > 0 AND TOTAL_RECEIVED_PRN > RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN <=  RECEIVABLE_PRN + OPENING_DUE_PRN
    THEN TOTAL_RECEIVED_PRN - RECEIVABLE_PRN
    -- WHEN OPENING_DUE_WSC > 0 AND RECEIVABLE_WSC = 0  AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC THEN TOTAL_RECEIVED_WSC
    
    END, 0)DEU_RCVD_PRN_NEW
    
    , NVL(CASE
    WHEN TOTAL_RECEIVED_PRN > OPENING_DUE_PRN + RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN  - (OPENING_DUE_PRN + RECEIVABLE_PRN)
    WHEN OPENING_DUE_PRN = 0 AND TOTAL_RECEIVED_PRN > RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN - RECEIVABLE_PRN
    END,0) ADV_RCVD_PRN_NEW 
    , NVL(CASE 
    WHEN OPENING_ADVANCE_PRN > 0 AND  TOTAL_RECEIVED_PRN < RECEIVABLE_PRN AND OPENING_ADVANCE_PRN <= RECEIVABLE_PRN  - TOTAL_RECEIVED_PRN 
    THEN OPENING_ADVANCE_PRN
    WHEN OPENING_ADVANCE_PRN > 0 AND TOTAL_RECEIVED_PRN < RECEIVABLE_PRN AND OPENING_ADVANCE_PRN > RECEIVABLE_PRN  - TOTAL_RECEIVED_PRN 
    THEN RECEIVABLE_PRN - TOTAL_RECEIVED_PRN
    END,0) ADVANCE_ADJ_PRN
    -----------------------------------------------------------------------------------------------------------------------------                                
    , TODAYS_RCVBLE , TD_TTL_RCVD, REBATE_AMT
    , TODAYS_RCVBLE_PRN, TD_TTL_RCVD_PRN
    
    , NVL(CASE 
    WHEN OPENING_ADVANCE_WSC > 0 AND  TD_TTL_RCVD < TODAYS_RCVBLE AND OPENING_ADVANCE_WSC <= TODAYS_RCVBLE  - TD_TTL_RCVD 
    THEN OPENING_ADVANCE_WSC
    WHEN OPENING_ADVANCE_WSC > 0 AND TD_TTL_RCVD < TODAYS_RCVBLE AND OPENING_ADVANCE_WSC > TODAYS_RCVBLE  - TD_TTL_RCVD 
    THEN TODAYS_RCVBLE - TD_TTL_RCVD
    --TODAYS_RCVBLE
    WHEN  TODAYS_RCVBLE > 0 AND TD_TTL_RCVD = 0 AND RECEIVABLE_WSC <= PRV_TTL_RCVD THEN  TODAYS_RCVBLE -- CORRECTION FOR INCORRECT ADVANCE ADJUST AMOUNT 30112023
    --WHEN  TODAYS_RCVBLE > 0 AND TD_TTL_RCVD > 0 AND TD_TTL_RCVD < TODAYS_RCVBLE  AND TODAYS_RCVBLE <= PRV_TTL_RCVD THEN  TODAYS_RCVBLE
    -- IF  ADVANCE BALANCE CREATE IN THE MONTH
    WHEN NVL(CLS_ADV_WSC,0) > 1  AND  TD_TTL_RCVD < TODAYS_RCVBLE_PRN AND NVL(CLS_ADV_WSC,0) <= TODAYS_RCVBLE  - TD_TTL_RCVD 
    THEN NVL(CLS_ADV_WSC,0)
    END,0) TD_ADVANCE_ADJUST_WSC
    
    , NVL(CASE 
    WHEN OPENING_ADVANCE_PRN > 0 AND  TD_TTL_RCVD_PRN < TODAYS_RCVBLE_PRN AND OPENING_ADVANCE_PRN <= TODAYS_RCVBLE_PRN  - TD_TTL_RCVD_PRN 
    THEN OPENING_ADVANCE_PRN
    WHEN OPENING_ADVANCE_PRN > 0 AND TD_TTL_RCVD_PRN < TODAYS_RCVBLE_PRN AND OPENING_ADVANCE_PRN > TODAYS_RCVBLE_PRN  - TD_TTL_RCVD_PRN 
    THEN TODAYS_RCVBLE_PRN - TD_TTL_RCVD_PRN
    --TODAYS_RCVBLE
    WHEN  TODAYS_RCVBLE_PRN > 0 AND TD_TTL_RCVD_PRN = 0 AND RECEIVABLE_PRN <= PRV_TTL_RCVD THEN  TODAYS_RCVBLE_PRN -- CORRECTION FOR INCORRECT ADVANCE ADJUST AMOUNT 30112023
    --WHEN  TODAYS_RCVBLE > 0 AND TD_TTL_RCVD > 0 AND TD_TTL_RCVD < TODAYS_RCVBLE  AND TODAYS_RCVBLE <= PRV_TTL_RCVD THEN  TODAYS_RCVBLE
    -- IF  ADVANCE BALANCE CREATE IN THE MONTH
    WHEN NVL(CLS_ADV_PRN,0) > 1  AND  TD_TTL_RCVD_PRN < TODAYS_RCVBLE_PRN AND NVL(CLS_ADV_PRN,0) <= TODAYS_RCVBLE_PRN  - TD_TTL_RCVD_PRN 
    THEN NVL(CLS_ADV_PRN,0)
    END,0) TD_ADVANCE_ADJUST_PRN
    , PRV_TTL_RCVD

    FROM
    (
        SELECT  T.COMPANY_BRANCH_CODE ,  T.SAMITY_CODE , T.MEMBER_ID,  T.LOAN_CODE  , T.DAFA_NO
        , B.OPENING_LOAN_WSC , B.OPENING_DUE_WSC , B.OPENING_ADVANCE_WSC
        , NVL(R.INSTALL_AMT,0) TODAYS_RCVBLE , NVL(R.PRN_AMT,0) TODAYS_RCVBLE_PRN
        ---- CHANGE ON 22_02_24 FOR NOT ADD ON CURRENT DATE MONTHLY LOAN INSTALL 
        
        --                        , (CASE WHEN B.LOAN_TYPE = 'W' THEN NVL(B.RECEIVABLE_WSC,0) + NVL(R.INSTALL_AMT,0) ELSE NVL(B.RECEIVABLE_WSC,0) END) RECEIVABLE_WSC  
        --                        , (CASE WHEN B.LOAN_TYPE = 'W' THEN NVL(B.RECEIVABLE_PRN,0) + NVL(R.PRN_AMT,0) ELSE NVL(B.RECEIVABLE_PRN,0) END) RECEIVABLE_PRN  
        --                        
        , ( NVL(B.RECEIVABLE_WSC,0) + NVL(R.INSTALL_AMT,0)) RECEIVABLE_WSC  
        , ( NVL(B.RECEIVABLE_PRN,0) + NVL(R.PRN_AMT,0)) RECEIVABLE_PRN  
        
        --, TOTAL_RECEIVED_WSC TILL_DAY_RCVD_WSC
        ,  (NVL(T.TOTAL_RCVD_CLC,0) + NVL(T.TOTAL_IRG_RCVD,0) + NVL(T.TOTAL_ADJ_AMT,0) + NVL(T.TOTAL_INS_ADJUST,0)) TD_TTL_RCVD
        , (NVL(T.TOTAL_RCVD_CLC,0) + NVL(T.TOTAL_IRG_RCVD,0) + NVL(T.TOTAL_ADJ_AMT,0) + NVL(T.TOTAL_INS_ADJUST,0)) + NVL(TOTAL_RECEIVED_WSC,0)  TOTAL_RECEIVED_WSC
        , NVL(TOTAL_RECEIVED_WSC,0) PRV_TTL_RCVD
        , OPENING_LOAN_PRN ,OPENING_DUE_PRN ,OPENING_ADVANCE_PRN 
        , (NVL(T.TOTAL_RCVD_PRN_CLC,0) + NVL(T.TOTAL_IRG_RCVD_PRN,0) + NVL(T.TOTAL_ADJUST_PRN,0) + NVL(T.INS_ADJ_PRN,0)) TD_TTL_RCVD_PRN
        , (NVL(T.TOTAL_RCVD_PRN_CLC,0) + NVL(T.TOTAL_IRG_RCVD_PRN,0) + NVL(T.TOTAL_ADJUST_PRN,0) + NVL(T.INS_ADJ_PRN,0)) + NVL(TOTAL_RECEIVED_PRN,0)  TOTAL_RECEIVED_PRN
        , REBATE_AMT, CLS_ADV_WSC,CLS_ADV_PRN
        FROM
            (
                    SELECT COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE  , DAFA_NO
                    
                    , SUM(TTL_CLC_RCVD) TOTAL_RCVD_CLC, SUM(TTL_CLC_PRN_RCVD) TOTAL_RCVD_PRN_CLC
                    , SUM(TTL_IRG_RCVD) TOTAL_IRG_RCVD, SUM(TTL_IRG_RCVD_PRN) TOTAL_IRG_RCVD_PRN
                    , SUM(TTL_CLC_RCVD) + SUM(TTL_IRG_RCVD) TOTAL_CASH_RCVD
                    , SUM(TTL_CLC_PRN_RCVD) + SUM(TTL_IRG_RCVD_PRN) TOTAL_CASH_RCVD_PRN
                    , SUM(ADJUST_AMT) TOTAL_ADJ_AMT , SUM(ADJUST_AMT_PRN) TOTAL_ADJUST_PRN
                    , SUM(TTL_INS_ADJUST) TOTAL_INS_ADJUST, SUM(INS_ADJUST_PRN) INS_ADJ_PRN
                    , SUM(INS_ADJUST_SC) INS_ADJ_SC
                    , NVL(SUM(CLC_REBATE_AMT),0) + NVL(SUM(IRG_RBT_AMT),0) + NVL(SUM(ADJ_REBATE_AMT),0) REBATE_AMT 
                    
                    FROM
                    (
                    SELECT C.COMPANY_BRANCH_CODE ,  C.SAMITY_CODE , C.MEMBER_ID,  C.LOAN_CODE , C.DAFA_NO
                    , 0 TTL_DISBURSE, 0 TTL_LOAN_FEE , 0 TTL_INS_AMT , 0 TTL_LIVE_STK_AMT
                    , TTL_CLC_RCVD , TTL_CLC_PRN_RCVD, CLC_REBATE_AMT
                    , 0 TTL_IRG_RCVD , 0 TTL_IRG_RCVD_PRN, 0 IRG_RBT_AMT
                    , 0 ADJUST_AMT , 0 ADJUST_AMT_PRN, 0 ADJUST_AMT_SC, 0 ADJ_REBATE_AMT
                    , 0 TTL_INS_ADJUST, 0 INS_ADJUST_PRN , 0 INS_ADJUST_SC, 0 INS_REBATE_AMT
                    , 0 AMOUNT_WO
                    FROM
                    (
                    SELECT    COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE , DAFA_NO
                    , NVL(SUM(TTL_INSTALL_AMT_RCVD),0) TTL_CLC_RCVD 
                    , NVL(SUM(AMOUNT_RCVD_PRN),0)  TTL_CLC_PRN_RCVD --, AMOUNT_RCVD_SC
                    , NVL(SUM(AMOUNT_REBATE),0) CLC_REBATE_AMT
                    FROM
                    (
                    SELECT  /*+ PARALLEL*/ 
                    A.COMPANY_BRANCH_CODE ,  A.SAMITY_CODE , A.MEMBER_ID, A.LOAN_CODE , A.DAFA_NO 
                    , A.TTL_INSTALL_AMT_RCVD , A.AMOUNT_REBATE, 
                    DECODE (
                    A.INSTALL_TYPE,
                    'S', 0,
                    'O', ROUND (A.TTL_INSTALL_AMT_RCVD, 2),
                    'P', ROUND (A.TTL_INSTALL_PRN_RCVD, 2),
                    'R', ROUND (A.TTL_INSTALL_PRN_RCVD, 2),
                    'T', ROUND (A.TTL_INSTALL_PRN_RCVD, 2),
                    ROUND (
                    A.TTL_INSTALL_AMT_RCVD
                    * B.DISBURSE_AMT
                    / (B.DISBURSE_AMT + B.TTL_SC),
                    2))
                    AMOUNT_RCVD_PRN,
                    DECODE (
                    A.INSTALL_TYPE,
                    'S', A.TTL_INSTALL_AMT_RCVD,
                    'O', 0,
                    'P', A.TTL_INSTALL_AMT_RCVD - ROUND (A.TTL_INSTALL_PRN_RCVD, 2),
                    'R', A.TTL_INSTALL_AMT_RCVD - ROUND (A.TTL_INSTALL_PRN_RCVD, 2),
                    'T', ROUND (A.TTL_INSTALL_SC_RCVD, 2),
                    A.TTL_INSTALL_AMT_RCVD
                    -   ROUND (A.TTL_INSTALL_AMT_RCVD, 2)
                    * B.DISBURSE_AMT
                    / (B.DISBURSE_AMT + B.TTL_SC))
                    AMOUNT_RCVD_SC
                    FROM COLLECTION_SHEET A, LOAN_BAL B
                    WHERE     (    A.COMPANY_CODE = B.COMPANY_CODE
                    AND A.COMPANY_BRANCH_CODE = B.COMPANY_BRANCH_CODE
                    AND A.SAMITY_CODE = B.SAMITY_CODE
                    AND A.FINANCE_CODE = B.FINANCE_CODE
                    AND A.PROJECT_CODE = B.PROJECT_CODE
                    AND A.COMPONENT_CODE = B.COMPONENT_CODE
                    AND A.MEMBER_ID = B.MEMBER_ID
                    AND A.LOAN_CODE = B.LOAN_CODE
                    AND A.DAFA_NO = B.DAFA_NO)
                    AND A.LOAN_CODE IS NOT NULL
                    AND A.COMPANY_CODE = '0133'
                    AND A.COMPANY_BRANCH_CODE =   '133' 
                    AND A.FINANCE_CODE = '01'
                    AND A.PROJECT_CODE = '02'
                    AND A.COMPONENT_CODE = '01'
                    AND COLLECT_DATE = '24-FEB-25'
                    -- AND A.DEVICE_FLAG IS NOT NULL 
                    )
                    GROUP BY COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE , DAFA_NO
                    ) C
                    
                    UNION ALL
                    
                    SELECT I.COMPANY_BRANCH_CODE ,  I.SAMITY_CODE , I.MEMBER_ID,  I.LOAN_CODE , I.DAFA_NO,  0 TTL_DISBURSE, 0 TTL_LOAN_FEE , 0 TTL_INS_AMT , 0 TTL_LIVE_STK_AMT
                    , 0 TTL_CLC_RCVD , 0 TTL_CLC_PRN_RCVD, 0 CLC_REBATE_AMT
                    , TTL_IRG_RCVD , TTL_IRG_RCVD_PRN, IRG_RBT_AMT
                    , 0 ADJUST_AMT , 0 ADJUST_AMT_PRN, 0 ADJUST_AMT_SC, 0 ADJ_REBATE_AMT
                    , 0 TTL_INS_ADJUST, 0 INS_ADJUST_PRN , 0 INS_ADJUST_SC , 0 INS_REBATE_AMT
                    , 0 AMOUNT_WO
                    
                    FROM
                    (
                    SELECT  COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE , DAFA_NO , NVL(SUM(AMOUNT_RCVD),0) TTL_IRG_RCVD
                    , NVL(SUM(AMOUNT_PRN_RCVD),0) TTL_IRG_RCVD_PRN, NVL(SUM(AMOUNT_REBATE),0) IRG_RBT_AMT
                    FROM LOAN_COLLECTION
                    WHERE COMPANY_CODE = '0133'
                    AND COMPANY_BRANCH_CODE = '133'
                    AND FINANCE_CODE = '01'
                    AND PROJECT_CODE = '02'
                    AND COMPONENT_CODE = '01'
                    AND COLLECT_DATE = '24-FEB-25'
                    GROUP BY COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE , DAFA_NO
                    ) I
                    UNION ALL
                    
                    SELECT A.COMPANY_BRANCH_CODE ,  A.SAMITY_CODE , A.MEMBER_ID, A.LOAN_CODE, DAFA_NO , 0 TTL_DISBURSE, 0 TTL_LOAN_FEE , 0 TTL_INS_AMT , 0 TTL_LIVE_STK_AMT
                    , 0 TTL_CLC_RCVD , 0 TTL_CLC_PRN_RCVD, 0 CLC_REBATE_AMT
                    , 0 TTL_IRG_RCVD , 0 TTL_IRG_RCVD_PRN, 0 IRG_RBT_AMT
                    , ADJUST_AMT , ADJUST_AMT_PRN, ADJUST_AMT_SC, ADJ_REBATE_AMT
                    , 0 TTL_INS_ADJUST, 0 INS_ADJUST_PRN , 0 INS_ADJUST_SC , 0 INS_REBATE_AMT
                    , 0 AMOUNT_WO
                    FROM
                    (
                    SELECT COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE, DAFA_NO  , NVL(SUM(AMOUNT_ADJUSTED),0)  ADJUST_AMT , NVL(SUM(AMOUNT_PRN_ADJUSTED),0) ADJUST_AMT_PRN, 
                    NVL(SUM(AMOUNT_SC_ADJUSTED),0) ADJUST_AMT_SC , NVL(SUM(AMOUNT_REBATE),0) ADJ_REBATE_AMT
                    FROM LOAN_SAVINGS_ADJUST
                    WHERE COMPANY_CODE = '0133'
                    AND COMPANY_BRANCH_CODE = '133'
                    AND FINANCE_CODE = '01'
                    AND PROJECT_CODE = '01'
                    AND COMPONENT_CODE = '02'
                    AND COLLECT_DATE = '24-FEB-25'
                    GROUP BY COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE , DAFA_NO
                    ) A
                    
                    UNION ALL
                    
                    SELECT IA.COMPANY_BRANCH_CODE ,  IA.SAMITY_CODE , IA.MEMBER_ID, IA.LOAN_CODE, IA.DAFA_NO , 0 TTL_DISBURSE, 0 TTL_LOAN_FEE , 0 TTL_INS_AMT , 0 TTL_LIVE_STK_AMT
                    , 0 TTL_CLC_RCVD , 0 TTL_CLC_PRN_RCVD, 0 CLC_REBATE_AMT
                    , 0 TTL_IRG_RCVD , 0 TTL_IRG_RCVD_PRN, 0 IRG_RBT_AMT
                    , 0 ADJUST_AMT , 0 ADJUST_AMT_PRN, 0 ADJUST_AMT_SC, 0 ADJ_REBATE_AMT
                    , TTL_INS_ADJUST, INS_ADJUST_PRN , INS_ADJUST_SC, REBATE_AMT INS_REBATE_AMT
                    , 0 AMOUNT_WO
                    FROM
                    (
                    SELECT COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE, DAFA_NO  , SUM(AMOUNT_ADJUSTED) TTL_INS_ADJUST , SUM(AMOUNT_PRN_ADJUSTED) INS_ADJUST_PRN
                    , SUM(AMOUNT_SC_ADJUSTED) INS_ADJUST_SC , NVL(SUM(AMOUNT_REBATE),0) REBATE_AMT
                    FROM LOAN_INS_ADJUST
                    WHERE COMPANY_CODE = '0133'
                    AND COMPANY_BRANCH_CODE = '133'
                    AND FINANCE_CODE = '01'
                    AND PROJECT_CODE = '02'
                    AND COMPONENT_CODE = '01'
                    AND COLLECT_DATE = '24-FEB-25'
                    GROUP BY COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE , DAFA_NO
                    ) IA
                    
                    )
                GROUP BY COMPANY_BRANCH_CODE ,  SAMITY_CODE , MEMBER_ID,  LOAN_CODE , DAFA_NO     
        )  T  
        JOIN
        (
        SELECT 
        COMPANY_BRANCH_CODE , MNYR ,--  V_WKYR, '24-FEB-25',
        SAMITY_CODE ,MEMBER_ID ,LOAN_CODE ,DAFA_NO ,
        OPENING_LOAN_WSC ,OPENING_DUE_WSC ,OPENING_ADVANCE_WSC ,
        RECEIVABLE_WSC ,TOTAL_RECEIVED_WSC ,DUE_RCVD_WSC ,REG_RCVD_WSC ,ADV_RCVD_WSC ,
        OPENING_LOAN_PRN ,OPENING_DUE_PRN ,OPENING_ADVANCE_PRN ,
        RECEIVABLE_PRN ,TOTAL_RECEIVED_PRN ,DUE_RCVD_PRN ,REG_RCVD_PRN , ADV_RCVD_PRN ,
        UPDATE_BY ,UPDATE_TIME ,
        ADVANCE_ADJUST_WSC ,ADVANCE_ADJ_PRN ,
        MONTH_TTL_RCVBLE_WSC ,MONTH_TTL_RCVBLE_PRN ,MONTH_TTL_REG_RCVD_WSC ,MONTH_TTL_REG_RCVD_PRN ,
        LOAN_TYPE ,RECOVERY_FLAG ,RECOVERY_DATE ,
        CLS_LOAN_WSC ,CLS_DUE_WSC ,CLS_ADV_WSC ,
        CLS_LOAN_PRN ,CLS_DUE_PRN ,CLS_ADV_PRN ,
        LLP_AGE_CODE_OPN ,LLP_PCT_OPN ,LLP_DAYS_OPN ,
        INSTALL_AMT ,LLP_CM_DAYS ,LLP_CLASS_OPN ,
        CM_DUE_WSC ,CM_DUE_PRN ,LLP_CUR_DAYS ,LLP_CUR_CLASS ,
        DISBURSE_DATE ,DISBURSE_AMT ,NEW_DISBURSE_FLAG ,
        TR_OUT_FLAG ,TR_IN_FLAG ,CO_ID ,DISBURSE_AMT_WSC 
        FROM MF_LOAN_REALIZATION
        WHERE MNYR = '08/2024'
        AND COMPANY_BRANCH_CODE = '133'
        ---AND TRANS_DAY = '27-FEB-22'
        ) B
        ON
        (
        T.COMPANY_BRANCH_CODE = B.COMPANY_BRANCH_CODE
        AND T.SAMITY_CODE = B.SAMITY_CODE
        AND T.MEMBER_ID = B.MEMBER_ID
        AND T.LOAN_CODE = B.LOAN_CODE
        AND T.DAFA_NO = B.DAFA_NO
        )
        
        LEFT JOIN
        (
        SELECT COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , INSTALL_NO , INSTALL_DT , INSTALL_AMT , PRN_AMT , SC_AMT , ACC_CLOSE_FLAG
        FROM MF_LRPS_ARCHIVE
        WHERE MNYR = '08/2024'
        AND COMPANY_BRANCH_CODE = '133'
        AND FINANCE_CODE = '01'
        AND PROJECT_CODE = '02'
        AND COMPONENT_CODE = '01'
        --AND WKYR = ''
        AND INSTALL_DT = '24-FEB-25'
        AND ACC_CLOSE_FLAG IS NULL
        
        ) R
        ON
        (
        T.COMPANY_BRANCH_CODE = R.COMPANY_BRANCH_CODE
        AND T.SAMITY_CODE = R.SAMITY_CODE
        AND T.MEMBER_ID = R.MEMBER_ID
        AND T.LOAN_CODE = R.LOAN_CODE
        AND T.DAFA_NO = R.DAFA_NO
        )
        
        WHERE NVL(T.TOTAL_RCVD_CLC,0) + NVL(T.TOTAL_IRG_RCVD,0) + NVL(T.TOTAL_ADJ_AMT,0) + NVL(T.TOTAL_INS_ADJUST,0) + NVL(R.INSTALL_AMT,0) > 0 
      --  AND T.SAMITY_CODE = '025'
        --AND T.MEMBER_ID = '00117'
    )
;
