------------------------ Consolidate

SELECT COUNT(DISTINCT COMPANY_BRANCH_CODE||SAMITY_CODE||MEMBER_ID) TOTAL_RUNNING_DUE_LOANEE , SUM( LOAN_OD_PRN) TOTAL_RUNNING_DUE_AMT
FROM LOAN_BAL_MNYR
WHERE COMPANY_CODE = '0177'
AND MNYR = '06/2024'
AND LOAN_OVERDUE > 0
AND LOAN_OVERDUE != LOAN_OUTSTANDING
;

--------------------------- Branch  Wise

SELECT ZONE_NAME , AREA_NAME , COMPANY_BRANCH_NAME , C.COMPANY_BRANCH_CODE , TOTAL_RUNNING_DUE_LOANEE, TOTAL_RUNNING_DUE_AMT
FROM
    (
    SELECT COMPANY_BRANCH_CODE , COUNT(DISTINCT COMPANY_BRANCH_CODE||SAMITY_CODE||MEMBER_ID) TOTAL_RUNNING_DUE_LOANEE , SUM(LOAN_OD_PRN) TOTAL_RUNNING_DUE_AMT
    FROM LOAN_BAL_MNYR
    WHERE COMPANY_CODE = '0177'
    AND MNYR = '06/2024'
    AND LOAN_OVERDUE > 0
    AND LOAN_OVERDUE != LOAN_OUTSTANDING
    GROUP BY COMPANY_BRANCH_CODE
    ) L
JOIN  COMPANY_BRANCH_INFO C
ON
    (
        L.COMPANY_BRANCH_CODE = C.COMPANY_BRANCH_CODE
    )
ORDER BY ZONE_NAME , AREA_NAME , COMPANY_BRANCH_NAME  
;
