SELECT  COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO
------------------------------------------------------ DUE RECEIVED --- REGULAR RECEIVED ---- ADVANCE RECEIVED -----------

    -------------------------------------------------- WITH SC ----------------------------------------------------
    , OPENING_LOAN_WSC , OPENING_DUE_WSC , OPENING_ADVANCE_WSC
    , RECEIVABLE_WSC , TOTAL_RECEIVED_WSC
        , NVL(CASE
                WHEN OPENING_DUE_WSC >= RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC <= OPENING_DUE_WSC THEN TOTAL_RECEIVED_WSC
                WHEN OPENING_DUE_WSC >= RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC > OPENING_DUE_WSC THEN OPENING_DUE_WSC
                WHEN OPENING_DUE_WSC < RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC > OPENING_DUE_WSC THEN OPENING_DUE_WSC
                WHEN OPENING_DUE_WSC < RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC <= OPENING_DUE_WSC THEN TOTAL_RECEIVED_WSC
                END,0) DUE_RCVD_WSC
        , NVL(CASE

                WHEN OPENING_DUE_WSC >= RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC + RECEIVABLE_WSC  THEN RECEIVABLE_WSC
                WHEN OPENING_DUE_WSC > 0 AND OPENING_DUE_WSC < RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC + RECEIVABLE_WSC  THEN  RECEIVABLE_WSC
                WHEN OPENING_DUE_WSC > 0 AND OPENING_DUE_WSC < RECEIVABLE_WSC
                        AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC  THEN TOTAL_RECEIVED_WSC - OPENING_DUE_WSC
                -- IF DUE GRATER THAN RECEIVABLE AND RECEIVED GRATER THAN DUE AND LESS THAN DUE + RCVLBE THEN
                WHEN OPENING_DUE_WSC >= RECEIVABLE_WSC
                        AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC  AND  TOTAL_RECEIVED_WSC < OPENING_DUE_WSC + RECEIVABLE_WSC
                        THEN TOTAL_RECEIVED_WSC - OPENING_DUE_WSC  

                WHEN OPENING_DUE_WSC = 0 AND TOTAL_RECEIVED_WSC <= RECEIVABLE_WSC THEN TOTAL_RECEIVED_WSC
                WHEN OPENING_DUE_WSC = 0 AND TOTAL_RECEIVED_WSC >= RECEIVABLE_WSC THEN RECEIVABLE_WSC
                END,0) REG_RCVD_WSC

        , NVL(CASE
                WHEN TOTAL_RECEIVED_WSC > OPENING_DUE_WSC + RECEIVABLE_WSC THEN TOTAL_RECEIVED_WSC  - (OPENING_DUE_WSC + RECEIVABLE_WSC)
                WHEN OPENING_DUE_WSC = 0 AND TOTAL_RECEIVED_WSC > RECEIVABLE_WSC THEN TOTAL_RECEIVED_WSC - RECEIVABLE_WSC
                END,0) ADV_RCVD_WSC
         ------------------------------------------ ADVANCE ADJUST
         , NVL(CASE
                WHEN OPENING_ADVANCE_WSC > 0 AND  TOTAL_RECEIVED_WSC < RECEIVABLE_WSC AND OPENING_ADVANCE_WSC <= RECEIVABLE_WSC  - TOTAL_RECEIVED_WSC
                        THEN OPENING_ADVANCE_WSC
                 WHEN OPENING_ADVANCE_WSC > 0 AND TOTAL_RECEIVED_WSC < RECEIVABLE_WSC AND OPENING_ADVANCE_WSC > RECEIVABLE_WSC  - TOTAL_RECEIVED_WSC
                        THEN RECEIVABLE_WSC - TOTAL_RECEIVED_WSC
                END,0) ADVANCE_ADJUST_WSC

    ---------------------------------------------------- PRN ------------------------------------------------------------
    , OPENING_LOAN_PRN , OPENING_DUE_PRN  , OPENING_ADVANCE_PRN
    , RECEIVABLE_PRN , TOTAL_RECEIVED_PRN
                        , NVL(CASE
                                WHEN OPENING_DUE_PRN >= RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN <= OPENING_DUE_PRN THEN TOTAL_RECEIVED_PRN
                                WHEN OPENING_DUE_PRN >= RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN > OPENING_DUE_PRN THEN OPENING_DUE_PRN
                                WHEN OPENING_DUE_PRN < RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN > OPENING_DUE_PRN THEN OPENING_DUE_PRN
                                WHEN OPENING_DUE_PRN < RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN <= OPENING_DUE_PRN THEN TOTAL_RECEIVED_PRN
                                END,0) DUE_RCVD_PRN
                        ------------------------------------- REGULAR RCVD PRN
                        , NVL(CASE
                                --WHEN OPENING_DUE_PRN >= RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN < OPENING_DUE_PRN + RECEIVABLE_PRN  THEN TOTAL_RECEIVED_PRN  - OPENING_DUE_PRN
                                WHEN OPENING_DUE_PRN >= RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN >= OPENING_DUE_PRN + RECEIVABLE_PRN  THEN RECEIVABLE_PRN
                                WHEN OPENING_DUE_PRN > 0 AND OPENING_DUE_PRN < RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN >= OPENING_DUE_PRN + RECEIVABLE_PRN  THEN  RECEIVABLE_PRN
                                WHEN OPENING_DUE_PRN > 0 AND OPENING_DUE_PRN < RECEIVABLE_PRN
                                    AND TOTAL_RECEIVED_PRN >= OPENING_DUE_PRN  THEN TOTAL_RECEIVED_PRN - OPENING_DUE_PRN
                                -- IF DUE GRATER THAN RECEIVABLE AND RECEIVED GRATER THAN DUE AND LESS THAN DUE + RCVLBE THEN
                                WHEN OPENING_DUE_WSC >= RECEIVABLE_WSC
                                    AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC  AND  TOTAL_RECEIVED_WSC < OPENING_DUE_WSC + RECEIVABLE_WSC
                                    THEN TOTAL_RECEIVED_WSC - OPENING_DUE_WSC  

                                WHEN OPENING_DUE_PRN = 0 AND TOTAL_RECEIVED_PRN <= RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN
                                WHEN OPENING_DUE_PRN = 0 AND TOTAL_RECEIVED_PRN >= RECEIVABLE_PRN THEN RECEIVABLE_PRN
                                END,0) REG_RCVD_PRN

                        ------------ ADVANCE RECEIVED
                        , NVL(CASE
                                WHEN TOTAL_RECEIVED_PRN > OPENING_DUE_PRN + RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN  - (OPENING_DUE_PRN + RECEIVABLE_PRN)
                                --WHEN OPENING_DUE_PRN = 0 AND TOTAL_RECEIVED_PRN <= RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN
                                WHEN OPENING_DUE_PRN = 0 AND TOTAL_RECEIVED_PRN > RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN - RECEIVABLE_PRN
                                END,0) ADV_RCVD_PRN
                    ------------------------------------------ ADVANCE ADJUST PRN
                     , NVL(CASE
                            WHEN OPENING_ADVANCE_PRN > 0 AND  TOTAL_RECEIVED_PRN < RECEIVABLE_PRN AND OPENING_ADVANCE_PRN <= RECEIVABLE_PRN  - TOTAL_RECEIVED_PRN
                                    THEN OPENING_ADVANCE_PRN
                             WHEN OPENING_ADVANCE_PRN > 0 AND TOTAL_RECEIVED_PRN < RECEIVABLE_PRN AND OPENING_ADVANCE_PRN > RECEIVABLE_PRN  - TOTAL_RECEIVED_PRN
                                    THEN RECEIVABLE_PRN - TOTAL_RECEIVED_PRN
                            END,0) ADVANCE_ADJ_PRN
------------------END OF DUE RECEIVED ----- REGULAR RECEIVED ----------- ADVANCE RECEIVED ------------------------

-------------------------- START ---- REGULAR--DUE--ADVANCE METHOD -------------   08.12.2020

                ------------------- REGULAR RECEIVED -------------------

       ,  NVL(CASE  WHEN RECEIVABLE_WSC > 0 AND  TOTAL_RECEIVED_WSC <= RECEIVABLE_WSC THEN  TOTAL_RECEIVED_WSC  
                    WHEN RECEIVABLE_WSC > 0 AND  TOTAL_RECEIVED_WSC > RECEIVABLE_WSC THEN  RECEIVABLE_WSC
                END,0)REG_RCVD_WSC_NEW

        , NVL(CASE  WHEN OPENING_DUE_WSC > 0 AND TOTAL_RECEIVED_WSC >=  RECEIVABLE_WSC + OPENING_DUE_WSC THEN OPENING_DUE_WSC
                WHEN OPENING_DUE_WSC > 0 AND TOTAL_RECEIVED_WSC > RECEIVABLE_WSC AND TOTAL_RECEIVED_WSC <=  RECEIVABLE_WSC + OPENING_DUE_WSC
                        THEN TOTAL_RECEIVED_WSC - RECEIVABLE_WSC
               -- WHEN OPENING_DUE_WSC > 0 AND RECEIVABLE_WSC = 0  AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC THEN TOTAL_RECEIVED_WSC

                END, 0)DEU_RCVD_WSC_NEW

          , NVL(CASE
                WHEN TOTAL_RECEIVED_WSC > OPENING_DUE_WSC + RECEIVABLE_WSC THEN TOTAL_RECEIVED_WSC  - (OPENING_DUE_WSC + RECEIVABLE_WSC)
                WHEN OPENING_DUE_WSC = 0 AND TOTAL_RECEIVED_WSC > RECEIVABLE_WSC THEN TOTAL_RECEIVED_WSC - RECEIVABLE_WSC
                END,0) ADV_RCVD_WSC_NEW   

  ------------------- REGULAR RECEIVED PRINCIPAL-------------------

       ,  NVL(CASE  WHEN RECEIVABLE_PRN > 0 AND  TOTAL_RECEIVED_PRN <= RECEIVABLE_PRN THEN  TOTAL_RECEIVED_PRN  
                    WHEN RECEIVABLE_PRN > 0 AND  TOTAL_RECEIVED_PRN > RECEIVABLE_PRN THEN  RECEIVABLE_PRN
                END,0)REG_RCVD_PRN_NEW

        , NVL(CASE  WHEN OPENING_DUE_PRN > 0 AND TOTAL_RECEIVED_PRN >=  RECEIVABLE_PRN + OPENING_DUE_PRN THEN OPENING_DUE_PRN
                WHEN OPENING_DUE_PRN > 0 AND TOTAL_RECEIVED_PRN > RECEIVABLE_PRN AND TOTAL_RECEIVED_PRN <=  RECEIVABLE_PRN + OPENING_DUE_PRN
                        THEN TOTAL_RECEIVED_PRN - RECEIVABLE_PRN
               -- WHEN OPENING_DUE_WSC > 0 AND RECEIVABLE_WSC = 0  AND TOTAL_RECEIVED_WSC >= OPENING_DUE_WSC THEN TOTAL_RECEIVED_WSC

                END, 0)DEU_RCVD_PRN_NEW

          , NVL(CASE
                WHEN TOTAL_RECEIVED_PRN > OPENING_DUE_PRN + RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN  - (OPENING_DUE_PRN + RECEIVABLE_PRN)
                WHEN OPENING_DUE_PRN = 0 AND TOTAL_RECEIVED_PRN > RECEIVABLE_PRN THEN TOTAL_RECEIVED_PRN - RECEIVABLE_PRN
                END,0) ADV_RCVD_PRN_NEW                      


    FROM
        (
        SELECT COMPANY_BRANCH_CODE,  SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO --, MNYR

                , SUM(OPN_LOAN_WSC) OPENING_LOAN_WSC , SUM(OPN_DUE_WSC) OPENING_DUE_WSC
                , SUM(OPN_ADVANCE_WSC) OPENING_ADVANCE_WSC
                , SUM(RCVBLE_WSC) RECEIVABLE_WSC , SUM(TOTAL_RCVD_WSC) TOTAL_RECEIVED_WSC

                , SUM(OPN_LOAN_PRN) OPENING_LOAN_PRN , SUM(OPN_DUE_PRN) OPENING_DUE_PRN
                , SUM(OPN_ADVANCE_PRN) OPENING_ADVANCE_PRN
                , SUM(RCVBLE_PRN) RECEIVABLE_PRN , SUM(TOTAL_RCVD_PRN) TOTAL_RECEIVED_PRN
        FROM
            (
            SELECT COMPANY_BRANCH_CODE,  SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR
                , OPN_LOAN_WSC , OPN_DUE_WSC , OPN_ADVANCE_WSC , 0 RCVBLE_WSC , 0 TOTAL_RCVD_WSC
                , OPN_LOAN_PRN , OPN_DUE_PRN  , OPN_ADVANCE_PRN , 0 RCVBLE_PRN , 0 TOTAL_RCVD_PRN
            FROM  
                (
                SELECT /*+ INDEX(PK_LOAN_BAL_MNYR)*/ COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR --, WKYR, INSTALL_NO
                      , NVL(LOAN_OUTSTANDING,0) OPN_LOAN_WSC , NVL(LOAN_OVERDUE,0) OPN_DUE_WSC
                      , NVL(LOAN_ADVANCE,0) OPN_ADVANCE_WSC

                      , NVL(LOAN_OUT_PRN,0) OPN_LOAN_PRN , NVL(LOAN_OD_PRN,0) OPN_DUE_PRN
                      , NVL(LOAN_ADV_PRN,0) OPN_ADVANCE_PRN

                FROM LOAN_BAL_WKYR
                WHERE COMPANY_CODE = '0133'
                AND COMPANY_BRANCH_CODE = '003'
                AND FINANCE_CODE = '01'
                AND PROJECT_CODE = '01'
                AND COMPONENT_CODE = '01'
                AND MNYR = '08/2024'
                AND WKYR = (SELECT DISTINCT WKYR   FROM PROCESS_CONTROL WHERE PROCESS_DATE=  (SELECT /*+ INDEX(PK_PROCESS_CONTROL) */  MAX(PROCESS_DATE)
                               
                                FROM PROCESS_CONTROL
                                WHERE
                                COMPANY_CODE = '0133' AND
                                (COMPANY_BRANCH_CODE = '003'  OR '003' IS NULL)
                                AND
                                FINANCE_CODE = '01' AND
                                PROJECT_CODE = '01' AND
                                COMPONENT_CODE = '01' AND
                                MNYR = '08/2024' AND 
                                DAY_CLOSE_FLAG = 'Y'))
               
                )
            UNION ALL
            
             SELECT COMPANY_BRANCH_CODE,  SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR
                , OPN_LOAN_WSC , OPN_DUE_WSC , OPN_ADVANCE_WSC , 0 RCVBLE_WSC , 0 TOTAL_RCVD_WSC
                , OPN_LOAN_PRN , OPN_DUE_PRN  , OPN_ADVANCE_PRN , 0 RCVBLE_PRN , 0 TOTAL_RCVD_PRN
            FROM  
                (
                SELECT  L.COMPANY_BRANCH_CODE , L.SAMITY_CODE , L.MEMBER_ID , L.LOAN_CODE , L.DAFA_NO , L.MNYR --, WKYR, INSTALL_NO
                      , NVL(LOAN_OUTSTANDING,0) OPN_LOAN_WSC , NVL(LOAN_OVERDUE,0) OPN_DUE_WSC
                      , NVL(LOAN_ADVANCE,0) OPN_ADVANCE_WSC

                      , NVL(LOAN_OUT_PRN,0) OPN_LOAN_PRN , NVL(LOAN_OD_PRN,0) OPN_DUE_PRN
                      , NVL(LOAN_ADV_PRN,0) OPN_ADVANCE_PRN

                FROM LOAN_BAL_WKYR L, LOAN_BAL B
                WHERE L.COMPANY_CODE = B.COMPANY_CODE
                AND L.COMPANY_BRANCH_CODE = B.COMPANY_BRANCH_CODE
                AND L.SAMITY_CODE = B.SAMITY_CODE
                AND L.MEMBER_ID = B.MEMBER_ID
                AND L.LOAN_CODE = B.LOAN_CODE
                AND L.DAFA_NO = B.DAFA_NO
                AND B.TRANSFER_IN_FLAG ='Y'
                AND L.MNYR = B.BAL_MNYR
                AND L.WKYR=B.BAL_WKYR
                AND L.COMPANY_CODE = '0133'
                AND L.COMPANY_BRANCH_CODE = '003'
                AND L.FINANCE_CODE = '01'
                AND L.PROJECT_CODE = '01'
                AND L.COMPONENT_CODE = '01'
                AND L.MNYR ='09/2024'
                )
                 UNION ALL
                

          

            SELECT COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR
                , 0 OPN_LOAN_WSC , 0 OPN_DUE_WSC , 0 OPN_ADVANCE_WSC ,  RCVBLE_WSC ,  TOTAL_RCVD_WSC
                , 0 PN_LOAN , 0 OPN_DUE  , 0 OPN_ADVANCE,  RCVBLE_PRN , TOTAL_RCVD_PRN
            FROM
                (
                SELECT  /*+ INDEX(PK_LOAN_BAL_WKYR)*/  COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR  
                           , NVL(SUM(LOAN_RCVBLE),0) RCVBLE_WSC , NVL(SUM(TTL_INSTALL_AMT_RCVD),0) TOTAL_RCVD_WSC
                            , NVL(SUM(LOAN_RCVBLE_PRN),0) RCVBLE_PRN
                            , NVL(SUM(TTL_INST_PRN_RCVD),0) TOTAL_RCVD_PRN
                FROM LOAN_BAL_WKYR
                WHERE COMPANY_CODE = '0133'
                AND COMPANY_BRANCH_CODE = '003'
                AND FINANCE_CODE = '01'
                AND PROJECT_CODE = '01'
                AND COMPONENT_CODE = '01'
                AND MNYR = '09/2024'
                AND WKYR <> '36/2024'
                --AND SAMITY_CODE = '00011028'
                --AND MEMBER_ID = '0001114147'
                GROUP BY COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR
                )
union all
                 SELECT COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR
                , 0 OPN_LOAN_WSC , 0 OPN_DUE_WSC , 0 OPN_ADVANCE_WSC ,  RCVBLE_WSC ,  TOTAL_RCVD_WSC
                , 0 PN_LOAN , 0 OPN_DUE  , 0 OPN_ADVANCE,  RCVBLE_PRN , TOTAL_RCVD_PRN
            FROM
                (
                SELECT /*+ INDEX(PK_LOAN_BAL_WKYR)*/ COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR  
                         , NVL(SUM(LOAN_RCVBLE),0) RCVBLE_WSC , 0 TOTAL_RCVD_WSC
                            , NVL(SUM(LOAN_RCVBLE_PRN),0) RCVBLE_PRN
                            , 0 TOTAL_RCVD_PRN
                FROM LOAN_BAL_WKYR
                WHERE COMPANY_CODE = '0133'
                AND COMPANY_BRANCH_CODE = '003'
                AND FINANCE_CODE = '01'
                AND PROJECT_CODE = '01'
                AND COMPONENT_CODE = '01'
                AND MNYR = '09/2024'
                AND WKYR = '36/2024'
               AND SAMITY_CODE IN
    (
        SELECT /*+ INDEX(PK_COLLECTION_SHEET)*/ DISTINCT SAMITY_CODE
        FROM COLLECTION_SHEET
        WHERE COMPANY_CODE = '0133'
                AND COMPANY_BRANCH_CODE = '003'
                AND FINANCE_CODE = '01'
                AND PROJECT_CODE = '01'
                AND COMPONENT_CODE = '01'
                AND MNYR = '09/2024'
        AND WKYR =  '36/2024'
   
    )
            
                GROUP BY COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR
                )
                
union all
                 SELECT COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR
                , 0 OPN_LOAN_WSC , 0 OPN_DUE_WSC , 0 OPN_ADVANCE_WSC ,  RCVBLE_WSC ,  TOTAL_RCVD_WSC
                , 0 PN_LOAN , 0 OPN_DUE  , 0 OPN_ADVANCE,  RCVBLE_PRN , TOTAL_RCVD_PRN
            FROM
                (
                SELECT /*+ INDEX(PK_LOAN_BAL_WKYR)*/ COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR  
                         , 0 RCVBLE_WSC , NVL(SUM(TTL_INSTALL_AMT_RCVD),0) TOTAL_RCVD_WSC
                            , 0 RCVBLE_PRN
                            , NVL(SUM(TTL_INST_PRN_RCVD),0) TOTAL_RCVD_PRN
                FROM LOAN_BAL_WKYR
                WHERE  COMPANY_CODE = '0133'
                AND COMPANY_BRANCH_CODE = '003'
                AND FINANCE_CODE = '01'
                AND PROJECT_CODE = '01'
                AND COMPONENT_CODE = '01'
                AND MNYR = '09/2024'
                AND WKYR =  '36/2024'
                
                GROUP BY COMPANY_BRANCH_CODE , SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO , MNYR)
            )
        GROUP BY COMPANY_BRANCH_CODE,  SAMITY_CODE , MEMBER_ID , LOAN_CODE , DAFA_NO --, MNYR
     )
