-- # MF_LOAN_REALIZATION
    CREATE TABLE MF_LOAN_REALIZATION (
    COMPANY_CODE             VARCHAR2(4 BYTE),
    COMPANY_BRANCH_CODE      VARCHAR2(4 BYTE),
    FINANCE_CODE             VARCHAR2(2 BYTE),
    PROJECT_CODE             VARCHAR2(2 BYTE),
    COMPONENT_CODE           VARCHAR2(2 BYTE),
    MNYR                     VARCHAR2(7 BYTE),
    SAMITY_CODE              VARCHAR2(10 BYTE),
    MEMBER_ID                VARCHAR2(10 BYTE),
    LOAN_CODE                VARCHAR2(3 BYTE),
    DAFA_NO                  NUMBER(8, 0),
    OPENING_LOAN_WSC         NUMBER(15, 0),
    OPENING_DUE_WSC          NUMBER(15, 0),
    OPENING_ADVANCE_WSC      NUMBER(15, 0),
    RECEIVABLE_WSC           NUMBER(15, 0),
    TOTAL_RECEIVED_WSC       NUMBER(15, 0),
    DUE_RCVD_WSC             NUMBER(15, 0),
    REG_RCVD_WSC             NUMBER(15, 0),
    ADV_RCVD_WSC             NUMBER(15, 0),
    OPENING_LOAN_PRN         NUMBER(16, 2),
    OPENING_DUE_PRN          NUMBER(16, 2),
    OPENING_ADVANCE_PRN      NUMBER(16, 2),
    RECEIVABLE_PRN           NUMBER(16, 2),
    TOTAL_RECEIVED_PRN       NUMBER(16, 2),
    DUE_RCVD_PRN             NUMBER(16, 2),
    REG_RCVD_PRN             NUMBER(16, 2),
    ADV_RCVD_PRN             NUMBER(16, 2),
    UPDATE_BY                VARCHAR2(30 BYTE),
    UPDATE_TIME              TIMESTAMP(6),
    ADVANCE_ADJUST_WSC       NUMBER(16, 0),
    ADVANCE_ADJ_PRN          NUMBER(16, 0),
    MONTH_TTL_RCVBLE_WSC     NUMBER(16, 0),
    MONTH_TTL_RCVBLE_PRN     NUMBER(16, 0),
    MONTH_TTL_REG_RCVD_WSC   NUMBER(16, 0),
    MONTH_TTL_REG_RCVD_PRN   NUMBER(16, 0),
    LOAN_TYPE                VARCHAR2(1 BYTE),
    RECOVERY_FLAG            VARCHAR2(1 BYTE),
    RECOVERY_DATE            DATE,
    SERIAL_NO                NUMBER,
    CLS_LOAN_WSC             NUMBER(15, 0),
    CLS_DUE_WSC              NUMBER(15, 0),
    CLS_ADV_WSC              NUMBER(15, 0),
    CLS_LOAN_PRN             NUMBER(15, 0),
    CLS_DUE_PRN              NUMBER(15, 0),
    CLS_ADV_PRN              NUMBER(15, 0),
    LLP_AGE_CODE_OPN         VARCHAR2(2 BYTE),
    LLP_PCT_OPN              NUMBER,
    LLP_DAYS_OPN             NUMBER(12, 0),
    INSTALL_AMT              NUMBER(12, 0),
    LLP_CM_DAYS              NUMBER(12, 0),
    LLP_CLASS_OPN            VARCHAR2(2 BYTE),
    CM_DUE_WSC               NUMBER(12, 0),
    CM_DUE_PRN               NUMBER(12, 0),
    LLP_CUR_DAYS             NUMBER(8, 0),
    LLP_CUR_CLASS            VARCHAR2(2 BYTE),
    DISBURSE_DATE            DATE,
    DISBURSE_AMT             NUMBER(12, 0),
    NEW_DISBURSE_FLAG        CHAR(1 BYTE),
    TR_OUT_FLAG              VARCHAR2(1 BYTE),
    TR_IN_FLAG               VARCHAR2(1 BYTE),
    CO_ID                    VARCHAR2(10 BYTE),
    DISBURSE_AMT_WSC         NUMBER(15, 0),
    CASH_TRANS_DATE          DATE,
    LOAN_ADJUST_DATE         DATE,
    INS_BY                   VARCHAR2(30 BYTE),
    INS_DATE                 DATE,
    UPD_BY                   VARCHAR2(30 BYTE),
    UPD_DATE                 DATE,
    CONSTRAINT MF_LOAN_REALIZATION_PK PRIMARY KEY ( COMPANY_CODE,
                                                      COMPANY_BRANCH_CODE,
                                                      FINANCE_CODE,
                                                      PROJECT_CODE,
                                                      COMPONENT_CODE,
                                                      MNYR,
                                                      SAMITY_CODE,
                                                      MEMBER_ID,
                                                      LOAN_CODE,
                                                      DAFA_NO )
);

# Alter Statement if missing columns any schema for this table

        ALTER TABLE SKS.MF_LOAN_REALIZATION ADD ( 
            FINANCE_CODE VARCHAR2(2 BYTE), 
            PROJECT_CODE VARCHAR2(2 BYTE), 
            COMPONENT_CODE VARCHAR2(2 BYTE), 
            CLS_LOAN_WSC NUMBER(15, 0), 
            CLS_DUE_WSC NUMBER(15, 0), 
            CLS_ADV_WSC NUMBER(15, 0), 
            CLS_LOAN_PRN NUMBER(15, 0), 
            CLS_DUE_PRN NUMBER(15, 0), 
            CLS_ADV_PRN NUMBER(15, 0), 
            LLP_AGE_CODE_OPN VARCHAR2(2 BYTE), 
            LLP_PCT_OPN NUMBER, 
            LLP_DAYS_OPN NUMBER(12, 0), 
            INSTALL_AMT NUMBER(12, 0), 
            LLP_CM_DAYS NUMBER(12, 0), 
            CM_DUE_WSC NUMBER(12, 0), 
            CM_DUE_PRN NUMBER(12, 0), 
            LLP_CUR_DAYS NUMBER(8, 0), 
            LLP_CUR_CLASS VARCHAR2(2 BYTE), 
            DISBURSE_DATE DATE, 
            DISBURSE_AMT NUMBER(12, 0), 
            NEW_DISBURSE_FLAG CHAR(1 BYTE), 
            TR_OUT_FLAG VARCHAR2(1 BYTE), 
            TR_IN_FLAG VARCHAR2(1 BYTE), 
            CO_ID VARCHAR2(10 BYTE), 
            DISBURSE_AMT_WSC NUMBER(15, 0), 
            CASH_TRANS_DATE DATE, 
            LOAN_ADJUST_DATE DATE, 
            INS_BY VARCHAR2(30 BYTE), 
            INS_DATE DATE, 
            UPD_BY VARCHAR2(30 BYTE), 
            UPD_DATE DATE 
        );
# Add New Column   ----------------- Update last close date when process the procedure
 ALTER TABLE SKS.MF_LOAN_REALIZATION ADD ( 
        LAST_CLS_DATE DATE
);
